service: api
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x

  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'eu-central-1'}
  stackName: ${self:service}-${self:provider.stage}

  environment:
    TICKETS_RESOURCE_STACK: ${param:TICKETS_RESOURCE_STACK}

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: "npm"
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  fetchTickets:
    handler: src/ticket.fetch
    events:
      - httpApi:
          path: /{nextToken}
          method: get
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Query
        Resource: ${cf:${self:provider.environment.TICKETS_RESOURCE_STACK}.TicketsTableArn}

  fetchTicket:
    handler: src/ticket.fetch
    events:
      - httpApi:
          path: /tickets/{ticketID}
          method: get
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
        Resource: ${cf:${self:provider.environment.TICKETS_RESOURCE_STACK}.TicketsTableArn}
  
  updateTicket:
    handler: src/ticket.update
    events:
      - httpApi:
          path: /tickets/update/{ticketID}
          method: post
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:UpdateItem
        Resource: ${cf:${self:provider.environment.TICKETS_RESOURCE_STACK}.TicketsTableArn}
  
  closeTicket:
    handler: src/ticket.close
    events:
      - httpApi:
          path: /tickets/close/{ticketID}
          method: delete
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DeleteItem
        Resource: ${cf:${self:provider.environment.TICKETS_RESOURCE_STACK}.TicketsTableArn}

  openTicket:
    handler: src/ticket.open
    events:
      - httpApi:
          path: /tickets/open/{ticketID}
          method: post
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource: ${cf:${self:provider.environment.TICKETS_RESOURCE_STACK}.TicketsTableArn}

resources:
  - Outputs:
      AwsRegion:
        Value: ${opt:region, self:provider.region}