service: tickets
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  profile: vm # specifying a specific aws profile

  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'eu-central-1'}
  stackName: ${self:service}-${self:provider.stage}

resources:
  - ${file(ticketsTable.yml)}

  - Outputs:
      TicketsTableID:
        Value: !Ref TicketsTable
      TicketsTableArn:
        Value: !GetAtt TicketsTable.Arn
      CFStack:
        Value: ${self:provider.stackName}