name: CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: ci-workflow
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install serverless framework
        run: npm i -g serverless

      - name: Install dependencies
        run: npm i && cd services/api && npm && cd ../../resources/tickets && npm i && cd ../..

      - name: Deploy ephemeral environment
        run: serverless deploy --stage ${{ github.run_id }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Test api service
        run: cd services/api && yarn export-env ${{ github.run_id }} && yarn test-ci && cd ../..
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Remove ephermeral environment
        run: serverless remove --stage ${{ github.run_id }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
