name: Deploy

on:
  push:
    branches:
      - dev
      - staging
      - prod
  pull_request:
    branches:
      - prod
      - staging
      - dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install serverless framework
      run: npm i -g serverless

    - name: Install dependencies
      run: npm i && cd services/api && npm i && cd ../../resources/tickets && npm i && cd ../..

    - name: Deploy environment
      run: serverless deploy --stage ${{ steps.branch-name.outputs.current_branch }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
